server:
  port: 3333

spring:
  cloud:
    gateway:
      routes:
      - id: welcome-api
        uri: lb://WELCOME
        predicates:
        - Path=/welcome
      - id: greek-api
        uri: lb://GREEK
        predicates:
        - Path=/greek
        
  application:
    name: CLOUD-API-GATEWAY